---

- hosts: web
  become: yes

  vars:
          pkgname: nginx
  tasks:
          - name: install nginx
            apt: name='{{pkgname}}' state=present
            notify: start nginx

  handlers:
          - name: start nginx
            service: name='{{pkgname}}' state=started








